services:
  api:
    build: .
    container_name: es10p-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: es10p-frontend
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped