"""Interfaces (protocolos) de almacenamiento del módulo de autenticación."""

from typing import Protocol

from app.domain.entities import Session, User, VerificationToken


class UserStore(Protocol):
    def add(self, user: User) -> None: ...

    def get_by_id(self, user_id: str) -> User | None: ...

    def get_by_username(self, username: str) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def update(self, user: User) -> None: ...


class SessionStore(Protocol):
    def add(self, session: Session) -> None: ...

    def get(self, token_hash: str) -> Session | None: ...

    def revoke(self, token_hash: str) -> None: ...


class VerificationStore(Protocol):
    def add(self, token: VerificationToken) -> None: ...

    def get(self, token_hash: str) -> VerificationToken | None: ...

    def mark_used(self, token_hash: str) -> None: ...