"""Generic single-database configuration template.

https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the.ini-file
"""
from alembic import op
import sqlalchemy as sa


"""add avatar_data and avatar_content_type columns to users table

Revision ID: 19bf59be156a
Revises: 0001_initial
Create Date: 2026-08-17 22:42:56.904571
"""
from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19bf59be156a'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_data', postgresql.BYTEA(), nullable=True))
    op.add_column('users', sa.Column('avatar_content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_content_type')
    op.drop_column('users', 'avatar_data')
    # ### end Alembic commands ###
